% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={MovieLens\_RecommendationSystem},
  pdfauthor={Chhaya Mudgal},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering

\title{MovieLens\_RecommendationSystem}
\author{Chhaya Mudgal}
\date{12/2/2020}

\begin{document}
\maketitle

\hypertarget{introduction-and-project-outline}{%
\section{Introduction and Project
Outline}\label{introduction-and-project-outline}}

Recommender Systems are systems that give recommendations to the user
based on ratings available. It requires large amount of data set which
is filtered, processed and trained. It looks at the different features
available in the data look at the usage to make suggestions. There are
different algorithms that can be used for building recommender Systems.
1) Collaborative Filtering, it is of 2 types a) Item Based b) User
Based. 2) Content Based 3) Classification Model. In each outcome there
are different set of predictors.

Project Problem- This is a Movie Lens Project to build a movie
recommender system using the dataset provided in the assignment. This
will require to train the data with different algorithms and compare the
accuracy of the algorithm against the validation set. Following steps
are taken to build a recommender system.

\begin{enumerate}
\def\labelenumi{\arabic{enumi})}
\tightlist
\item
  Load Data
\item
  Explore and Visualize data
\item
  Prepare Data.
\item
  Evaluate Algorithms.
\item
  Make Predictions and Present Results.
\end{enumerate}

\hypertarget{load-data}{%
\section{Load Data}\label{load-data}}

\hypertarget{load-data-and-install-library-packages}{%
\subsection{Load Data and Install Library
Packages}\label{load-data-and-install-library-packages}}

Using the script provided in the course Download data set Install
necessary library packages Create edx Data Set and Validation Set (final
hold-out test set)

Note: this process could take a couple of minutes

\begin{Shaded}
\begin{Highlighting}[]
\ControlFlowTok{if}\NormalTok{(}\OperatorTok{!}\KeywordTok{require}\NormalTok{(tidyverse)) }\KeywordTok{install.packages}\NormalTok{(}\StringTok{"tidyverse"}\NormalTok{, }\DataTypeTok{repos =} \StringTok{"http://cran.us.r-project.org"}\NormalTok{)}
\ControlFlowTok{if}\NormalTok{(}\OperatorTok{!}\KeywordTok{require}\NormalTok{(caret)) }\KeywordTok{install.packages}\NormalTok{(}\StringTok{"caret"}\NormalTok{, }\DataTypeTok{repos =} \StringTok{"http://cran.us.r-project.org"}\NormalTok{)}
\ControlFlowTok{if}\NormalTok{(}\OperatorTok{!}\KeywordTok{require}\NormalTok{(data.table)) }\KeywordTok{install.packages}\NormalTok{(}\StringTok{"data.table"}\NormalTok{, }\DataTypeTok{repos =} \StringTok{"http://cran.us.r-project.org"}\NormalTok{)}

\KeywordTok{library}\NormalTok{(tidyverse)}
\KeywordTok{library}\NormalTok{(caret)}
\KeywordTok{library}\NormalTok{(data.table)}

\CommentTok{### MovieLens 10M dataset:}
\CommentTok{### https://grouplens.org/datasets/movielens/10m/}
\CommentTok{### http://files.grouplens.org/datasets/movielens/ml-10m.zip}

\NormalTok{dl <-}\StringTok{ }\KeywordTok{tempfile}\NormalTok{()}
\KeywordTok{download.file}\NormalTok{(}\StringTok{"http://files.grouplens.org/datasets/movielens/ml-10m.zip"}\NormalTok{, dl)}

\NormalTok{ratings <-}\StringTok{ }\KeywordTok{fread}\NormalTok{(}\DataTypeTok{text =} \KeywordTok{gsub}\NormalTok{(}\StringTok{"::"}\NormalTok{, }\StringTok{"}\CharTok{\textbackslash{}t}\StringTok{"}\NormalTok{, }\KeywordTok{readLines}\NormalTok{(}\KeywordTok{unzip}\NormalTok{(dl, }\StringTok{"ml-10M100K/ratings.dat"}\NormalTok{))),}
                 \DataTypeTok{col.names =} \KeywordTok{c}\NormalTok{(}\StringTok{"userId"}\NormalTok{, }\StringTok{"movieId"}\NormalTok{, }\StringTok{"rating"}\NormalTok{, }\StringTok{"timestamp"}\NormalTok{))}

\NormalTok{movies <-}\StringTok{ }\KeywordTok{str_split_fixed}\NormalTok{(}\KeywordTok{readLines}\NormalTok{(}\KeywordTok{unzip}\NormalTok{(dl, }\StringTok{"ml-10M100K/movies.dat"}\NormalTok{)), }\StringTok{"}\CharTok{\textbackslash{}\textbackslash{}}\StringTok{::"}\NormalTok{, }\DecValTok{3}\NormalTok{)}
\KeywordTok{colnames}\NormalTok{(movies) <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"movieId"}\NormalTok{, }\StringTok{"title"}\NormalTok{, }\StringTok{"genres"}\NormalTok{)}

\CommentTok{##### if using R 3.6 or earlier:}
\NormalTok{movies <-}\StringTok{ }\KeywordTok{as.data.frame}\NormalTok{(movies) }\OperatorTok{%>%}\StringTok{ }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{movieId =} \KeywordTok{as.numeric}\NormalTok{(}\KeywordTok{levels}\NormalTok{(movieId))[movieId],}
                                           \DataTypeTok{title =} \KeywordTok{as.character}\NormalTok{(title),}
                                           \DataTypeTok{genres =} \KeywordTok{as.character}\NormalTok{(genres))}
\CommentTok{#### if using R 4.0 or later:}
\NormalTok{movies <-}\StringTok{ }\KeywordTok{as.data.frame}\NormalTok{(movies) }\OperatorTok{%>%}\StringTok{ }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{movieId =} \KeywordTok{as.numeric}\NormalTok{(movieId),}
                                           \DataTypeTok{title =} \KeywordTok{as.character}\NormalTok{(title),}
                                           \DataTypeTok{genres =} \KeywordTok{as.character}\NormalTok{(genres))}


\NormalTok{movielens <-}\StringTok{ }\KeywordTok{left_join}\NormalTok{(ratings, movies, }\DataTypeTok{by =} \StringTok{"movieId"}\NormalTok{)}

\CommentTok{### Validation set will be 10% of MovieLens data}
\KeywordTok{set.seed}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DataTypeTok{sample.kind=}\StringTok{"Rounding"}\NormalTok{) }\CommentTok{# if using R 3.5 or earlier, use `set.seed(1)`}
\NormalTok{test_index <-}\StringTok{ }\KeywordTok{createDataPartition}\NormalTok{(}\DataTypeTok{y =}\NormalTok{ movielens}\OperatorTok{$}\NormalTok{rating, }\DataTypeTok{times =} \DecValTok{1}\NormalTok{, }\DataTypeTok{p =} \FloatTok{0.1}\NormalTok{, }\DataTypeTok{list =} \OtherTok{FALSE}\NormalTok{)}
\NormalTok{edx <-}\StringTok{ }\NormalTok{movielens[}\OperatorTok{-}\NormalTok{test_index,]}
\NormalTok{temp <-}\StringTok{ }\NormalTok{movielens[test_index,]}

\CommentTok{### Make sure userId and movieId in validation set are also in edx set}
\NormalTok{validation <-}\StringTok{ }\NormalTok{temp }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{semi_join}\NormalTok{(edx, }\DataTypeTok{by =} \StringTok{"movieId"}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{semi_join}\NormalTok{(edx, }\DataTypeTok{by =} \StringTok{"userId"}\NormalTok{)}

\CommentTok{### Add rows removed from validation set back into edx set}
\NormalTok{removed <-}\StringTok{ }\KeywordTok{anti_join}\NormalTok{(temp, validation)}
\NormalTok{edx <-}\StringTok{ }\KeywordTok{rbind}\NormalTok{(edx, removed)}

\KeywordTok{rm}\NormalTok{(dl, ratings, movies, test_index, temp, movielens, removed)}
\end{Highlighting}
\end{Shaded}

\hypertarget{prepare-data}{%
\section{Prepare Data}\label{prepare-data}}

\hypertarget{create-training-and-test-sets-to-assess-the-accuracy-of-the-models.}{%
\subsection{Create training and test sets to assess the accuracy of the
models.}\label{create-training-and-test-sets-to-assess-the-accuracy-of-the-models.}}

\hypertarget{percent-of-edx-data-will-be-training-and-10-will-be-test-data-set}{%
\subsubsection{90 percent of edx data will be training and 10\% will be
test data
set}\label{percent-of-edx-data-will-be-training-and-10-will-be-test-data-set}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{set.seed}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DataTypeTok{sample.kind=}\StringTok{"Rounding"}\NormalTok{)}
\NormalTok{test_index <-}\StringTok{ }\KeywordTok{createDataPartition}\NormalTok{(}\DataTypeTok{y =}\NormalTok{ edx}\OperatorTok{$}\NormalTok{rating, }\DataTypeTok{times =} \DecValTok{1}\NormalTok{, }\DataTypeTok{p =} \FloatTok{0.1}\NormalTok{, }\DataTypeTok{list =} \OtherTok{FALSE}\NormalTok{)}
\NormalTok{train_set <-}\StringTok{ }\NormalTok{edx[}\OperatorTok{-}\NormalTok{test_index,]}
\NormalTok{temp <-}\StringTok{ }\NormalTok{edx[test_index,]}

\CommentTok{## Make sure userId and movieId in test set are also in train set}
\NormalTok{test_set <-}\StringTok{ }\NormalTok{temp }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{semi_join}\NormalTok{(train_set, }\DataTypeTok{by =} \StringTok{"movieId"}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{semi_join}\NormalTok{(train_set, }\DataTypeTok{by =} \StringTok{"userId"}\NormalTok{)}

\CommentTok{## Add rows removed from test set back into train set}
\NormalTok{removed <-}\StringTok{ }\KeywordTok{anti_join}\NormalTok{(temp, test_set)}
\NormalTok{train_set <-}\StringTok{ }\KeywordTok{rbind}\NormalTok{(train_set, removed)}

\KeywordTok{rm}\NormalTok{(test_index, temp, removed)}
\end{Highlighting}
\end{Shaded}

\hypertarget{explore-data}{%
\section{Explore Data}\label{explore-data}}

\hypertarget{in-order-to-build-model-we-first-need-to-look-at-the-data.}{%
\subsubsection{In order to build model we first need to look at the
data.}\label{in-order-to-build-model-we-first-need-to-look-at-the-data.}}

\hypertarget{dimensions-of-the-data-set}{%
\subsection{Dimensions of the data
set}\label{dimensions-of-the-data-set}}

\hypertarget{lets-find-out-the-total-number-of-columns-and-rows-in-the-edx-data-set.}{%
\subsubsection{Lets find out the total number of columns and rows in the
edx data
set.}\label{lets-find-out-the-total-number-of-columns-and-rows-in-the-edx-data-set.}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{dim}\NormalTok{(edx)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 9000055       6
\end{verbatim}

\hypertarget{peek-at-the-first-5-rows-of-the-data}{%
\subsection{Peek at the first 5 rows of the
data}\label{peek-at-the-first-5-rows-of-the-data}}

\hypertarget{we-peek-at-the-dataset-and-find-that-the-column-names-in-the-dataset-are}{%
\subsubsection{We peek at the dataset and find that the column names in
the dataset
are:}\label{we-peek-at-the-dataset-and-find-that-the-column-names-in-the-dataset-are}}

\hypertarget{userid-movieid-rating-timestamp-title-and-genre.}{%
\subsubsection{UserId, movieId, Rating, Timestamp, Title and
Genre.}\label{userid-movieid-rating-timestamp-title-and-genre.}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{head}\NormalTok{(edx)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    userId movieId rating timestamp                         title
## 1:      1     122      5 838985046              Boomerang (1992)
## 2:      1     185      5 838983525               Net, The (1995)
## 3:      1     292      5 838983421               Outbreak (1995)
## 4:      1     316      5 838983392               Stargate (1994)
## 5:      1     329      5 838983392 Star Trek: Generations (1994)
## 6:      1     355      5 838984474       Flintstones, The (1994)
##                           genres
## 1:                Comedy|Romance
## 2:         Action|Crime|Thriller
## 3:  Action|Drama|Sci-Fi|Thriller
## 4:       Action|Adventure|Sci-Fi
## 5: Action|Adventure|Drama|Sci-Fi
## 6:       Children|Comedy|Fantasy
\end{verbatim}

\hypertarget{summarize-edx-data}{%
\subsection{Summarize edx data}\label{summarize-edx-data}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(edx)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      userId         movieId          rating        timestamp        
##  Min.   :    1   Min.   :    1   Min.   :0.500   Min.   :7.897e+08  
##  1st Qu.:18124   1st Qu.:  648   1st Qu.:3.000   1st Qu.:9.468e+08  
##  Median :35738   Median : 1834   Median :4.000   Median :1.035e+09  
##  Mean   :35870   Mean   : 4122   Mean   :3.512   Mean   :1.033e+09  
##  3rd Qu.:53607   3rd Qu.: 3626   3rd Qu.:4.000   3rd Qu.:1.127e+09  
##  Max.   :71567   Max.   :65133   Max.   :5.000   Max.   :1.231e+09  
##     title              genres         
##  Length:9000055     Length:9000055    
##  Class :character   Class :character  
##  Mode  :character   Mode  :character  
##                                       
##                                       
## 
\end{verbatim}

\hypertarget{genres}{%
\subsection{Genres}\label{genres}}

\hypertarget{the-data-set-contains-797-different-combinations-of-genres.-here-is-the-list-of-the-first-six.}{%
\subsubsection{The data set contains 797 different combinations of
genres. Here is the list of the first
six.}\label{the-data-set-contains-797-different-combinations-of-genres.-here-is-the-list-of-the-first-six.}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{edx_genres <-}\StringTok{ }\NormalTok{edx }\OperatorTok{%>%}\StringTok{ }\KeywordTok{group_by}\NormalTok{(genres) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{summarise}\NormalTok{(}\DataTypeTok{n=}\KeywordTok{n}\NormalTok{()) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{head}\NormalTok{()}
\NormalTok{edx_genres}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 2
##   genres                                                 n
##   <chr>                                              <int>
## 1 (no genres listed)                                     7
## 2 Action                                             24482
## 3 Action|Adventure                                   68688
## 4 Action|Adventure|Animation|Children|Comedy          7467
## 5 Action|Adventure|Animation|Children|Comedy|Fantasy   187
## 6 Action|Adventure|Animation|Children|Comedy|IMAX       66
\end{verbatim}

\hypertarget{ratings}{%
\subsection{Ratings}\label{ratings}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{edx_ratings <-}\StringTok{ }\NormalTok{edx }\OperatorTok{%>%}\StringTok{ }\KeywordTok{group_by}\NormalTok{(rating) }\OperatorTok{%>%}\StringTok{ }\KeywordTok{summarize}\NormalTok{(}\DataTypeTok{n=}\KeywordTok{n}\NormalTok{())}
\NormalTok{edx_ratings}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 10 x 2
##    rating       n
##     <dbl>   <int>
##  1    0.5   85374
##  2    1    345679
##  3    1.5  106426
##  4    2    711422
##  5    2.5  333010
##  6    3   2121240
##  7    3.5  791624
##  8    4   2588430
##  9    4.5  526736
## 10    5   1390114
\end{verbatim}

\hypertarget{visualize-data}{%
\section{Visualize Data}\label{visualize-data}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{edx }\OperatorTok{%>%}\StringTok{ }\KeywordTok{group_by}\NormalTok{(rating) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{summarise}\NormalTok{(}\DataTypeTok{count=}\KeywordTok{n}\NormalTok{()) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{ggplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{rating, }\DataTypeTok{y=}\NormalTok{count)) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{geom_line}\NormalTok{() }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_point}\NormalTok{() }\OperatorTok{+}
\StringTok{  }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"Rating Distribution"}\NormalTok{, }\DataTypeTok{subtitle =} \StringTok{"Higher ratings are prevalent."}\NormalTok{) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{xlab}\NormalTok{(}\StringTok{"Rating"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ylab}\NormalTok{(}\StringTok{"Count"}\NormalTok{) }
\end{Highlighting}
\end{Shaded}

\includegraphics{MovieLens_RecommendationSystem_files/figure-latex/visualize-1.pdf}
\# Evaluate Algorithms \#\# ------------------Loss
Function---------------------- \#\#\# It is a means to evaluate how
specific algorithm behaves \#\#\# for a given data.If predictions
deviates too much from actual results, loss function \#\#\# R will be a
very large number. Optimization function help to reduce the error in
prediction.

\hypertarget{define-mean-absolute-error-mae}{%
\subsection{Define Mean Absolute Error
(MAE)}\label{define-mean-absolute-error-mae}}

\hypertarget{mean-absolute-error-is-the-average-of-sum-of-absolute-differences-between-predictions-and-actual-observations.}{%
\subsubsection{Mean absolute error, is the average of sum of absolute
differences between predictions and actual
observations.}\label{mean-absolute-error-is-the-average-of-sum-of-absolute-differences-between-predictions-and-actual-observations.}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{MAE <-}\StringTok{ }\ControlFlowTok{function}\NormalTok{(true_ratings, predicted_ratings)\{}
  \KeywordTok{mean}\NormalTok{(}\KeywordTok{abs}\NormalTok{(true_ratings }\OperatorTok{-}\StringTok{ }\NormalTok{predicted_ratings))}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\hypertarget{define-mean-squared-error-mse}{%
\subsection{Define Mean Squared Error
(MSE)}\label{define-mean-squared-error-mse}}

\hypertarget{mean-square-error-is-the-average-of-squared-difference-between-predictions-and-actual-observations.}{%
\subsubsection{Mean square error is the average of squared difference
between predictions and actual
observations.}\label{mean-square-error-is-the-average-of-squared-difference-between-predictions-and-actual-observations.}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{MSE <-}\StringTok{ }\ControlFlowTok{function}\NormalTok{(true_ratings, predicted_ratings)\{}
  \KeywordTok{mean}\NormalTok{((true_ratings }\OperatorTok{-}\StringTok{ }\NormalTok{predicted_ratings)}\OperatorTok{^}\DecValTok{2}\NormalTok{)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\hypertarget{define-root-mean-squared-error-rmse}{%
\subsection{Define Root Mean Squared Error
(RMSE)}\label{define-root-mean-squared-error-rmse}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{RMSE <-}\StringTok{ }\ControlFlowTok{function}\NormalTok{(true_ratings, predicted_ratings)\{}
  \KeywordTok{sqrt}\NormalTok{(}\KeywordTok{mean}\NormalTok{((true_ratings }\OperatorTok{-}\StringTok{ }\NormalTok{predicted_ratings)}\OperatorTok{^}\DecValTok{2}\NormalTok{))}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\hypertarget{simple-assumption-based-model}{%
\subsection{Simple Assumption Based
Model}\label{simple-assumption-based-model}}

\hypertarget{model-assumes-same-ratings-for-all-users.}{%
\subsubsection{Model assumes same ratings for all
users.}\label{model-assumes-same-ratings-for-all-users.}}

\hypertarget{if-we-predict-all-unknown-ratings-with-mu_i-we-obtain-the-following-rmse}{%
\subsubsection{If we predict all unknown ratings with mu\_i we obtain
the following
RMSE:}\label{if-we-predict-all-unknown-ratings-with-mu_i-we-obtain-the-following-rmse}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mu_hat <-}\StringTok{ }\KeywordTok{mean}\NormalTok{(train_set}\OperatorTok{$}\NormalTok{rating)}
\NormalTok{mu_hat}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 3.512456
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{naive_rmse <-}\StringTok{ }\KeywordTok{RMSE}\NormalTok{(test_set}\OperatorTok{$}\NormalTok{rating, mu_hat)}
\NormalTok{naive_rmse}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.060054
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{rmse_results <-}\StringTok{ }\KeywordTok{tibble}\NormalTok{(}\DataTypeTok{method =} \StringTok{"Just the average"}\NormalTok{, }\DataTypeTok{RMSE =}\NormalTok{ naive_rmse)}
\end{Highlighting}
\end{Shaded}

\hypertarget{including-movie-effect-to-the-model}{%
\subsection{Including Movie Effect to the
model}\label{including-movie-effect-to-the-model}}

\hypertarget{augment-our-previous-model-by-adding-the-term-b_i-to-represent-average-ranking-for-movie}{%
\subsubsection{Augment our previous model by adding the term b\_i to
represent average ranking for
movie}\label{augment-our-previous-model-by-adding-the-term-b_i-to-represent-average-ranking-for-movie}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mu <-}\StringTok{ }\KeywordTok{mean}\NormalTok{(train_set}\OperatorTok{$}\NormalTok{rating) }
\NormalTok{movie_avgs <-}\StringTok{ }\NormalTok{train_set }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{group_by}\NormalTok{(movieId) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{summarize}\NormalTok{(}\DataTypeTok{b_i =} \KeywordTok{mean}\NormalTok{(rating }\OperatorTok{-}\StringTok{ }\NormalTok{mu))}

\KeywordTok{qplot}\NormalTok{(b_i, }\DataTypeTok{data =}\NormalTok{ movie_avgs, }\DataTypeTok{bins =} \DecValTok{10}\NormalTok{, }\DataTypeTok{color =} \KeywordTok{I}\NormalTok{(}\StringTok{"black"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{MovieLens_RecommendationSystem_files/figure-latex/unnamed-chunk-1-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{predicted_ratings <-}\StringTok{ }\NormalTok{mu }\OperatorTok{+}\StringTok{ }\NormalTok{test_set }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{left_join}\NormalTok{(movie_avgs, }\DataTypeTok{by=}\StringTok{'movieId'}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{pull}\NormalTok{(b_i)}
\KeywordTok{RMSE}\NormalTok{(predicted_ratings, test_set}\OperatorTok{$}\NormalTok{rating)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.9429615
\end{verbatim}

\hypertarget{including-user-effect}{%
\subsection{Including User Effect}\label{including-user-effect}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{train_set }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{group_by}\NormalTok{(userId) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{summarize}\NormalTok{(}\DataTypeTok{b_u =} \KeywordTok{mean}\NormalTok{(rating)) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{filter}\NormalTok{(}\KeywordTok{n}\NormalTok{()}\OperatorTok{>=}\DecValTok{100}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{ggplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(b_u)) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{geom_histogram}\NormalTok{(}\DataTypeTok{bins =} \DecValTok{30}\NormalTok{, }\DataTypeTok{color =} \StringTok{"black"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{MovieLens_RecommendationSystem_files/figure-latex/unnamed-chunk-2-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{user_avgs <-}\StringTok{ }\NormalTok{train_set }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{left_join}\NormalTok{(movie_avgs, }\DataTypeTok{by=}\StringTok{'movieId'}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{group_by}\NormalTok{(userId) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{summarize}\NormalTok{(}\DataTypeTok{b_u =} \KeywordTok{mean}\NormalTok{(rating }\OperatorTok{-}\StringTok{ }\NormalTok{mu }\OperatorTok{-}\StringTok{ }\NormalTok{b_i))}


\NormalTok{predicted_ratings <-}\StringTok{ }\NormalTok{test_set }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{left_join}\NormalTok{(movie_avgs, }\DataTypeTok{by=}\StringTok{'movieId'}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{left_join}\NormalTok{(user_avgs, }\DataTypeTok{by=}\StringTok{'userId'}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{pred =}\NormalTok{ mu }\OperatorTok{+}\StringTok{ }\NormalTok{b_i }\OperatorTok{+}\StringTok{ }\NormalTok{b_u) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{pull}\NormalTok{(pred)}
\KeywordTok{RMSE}\NormalTok{(predicted_ratings, test_set}\OperatorTok{$}\NormalTok{rating)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.8646843
\end{verbatim}

\hypertarget{regularization}{%
\subsection{Regularization}\label{regularization}}

\hypertarget{a-technique-to-solve-over-fitting.}{%
\subsubsection{A technique to solve over
fitting.}\label{a-technique-to-solve-over-fitting.}}

\hypertarget{user-and-movie-effects-are-regularized-adding-a-penalty-factor-ux3bb-which-is-a-tuning-parameter.-we-define-a-number-of-values-for-ux3bb-and-use-the-regularization-function-to-pick-the-best-value-that-minimizes-the-rmse.}{%
\subsubsection{User and Movie effects are regularized adding a penalty
factor λ, which is a tuning parameter. We define a number \#\#\# of
values for λ and use the regularization function to pick the best value
that minimizes the
RMSE.}\label{user-and-movie-effects-are-regularized-adding-a-penalty-factor-ux3bb-which-is-a-tuning-parameter.-we-define-a-number-of-values-for-ux3bb-and-use-the-regularization-function-to-pick-the-best-value-that-minimizes-the-rmse.}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{test_set }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{left_join}\NormalTok{(movie_avgs, }\DataTypeTok{by=}\StringTok{'movieId'}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{residual =}\NormalTok{ rating }\OperatorTok{-}\StringTok{ }\NormalTok{(mu }\OperatorTok{+}\StringTok{ }\NormalTok{b_i)) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{arrange}\NormalTok{(}\KeywordTok{desc}\NormalTok{(}\KeywordTok{abs}\NormalTok{(residual))) }\OperatorTok{%>%}\StringTok{  }
\StringTok{  }\KeywordTok{slice}\NormalTok{(}\DecValTok{1}\OperatorTok{:}\DecValTok{10}\NormalTok{) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{pull}\NormalTok{(title)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] "From Justin to Kelly (2003)"      "Shawshank Redemption, The (1994)"
##  [3] "Shawshank Redemption, The (1994)" "Godfather, The (1972)"           
##  [5] "Godfather, The (1972)"            "Godfather, The (1972)"           
##  [7] "Godfather, The (1972)"            "Usual Suspects, The (1995)"      
##  [9] "Schindler's List (1993)"          "Schindler's List (1993)"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{movie_titles <-}\StringTok{ }\NormalTok{train_set }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{select}\NormalTok{(movieId, title) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{distinct}\NormalTok{()}


\NormalTok{movie_avgs }\OperatorTok{%>%}\StringTok{ }\KeywordTok{left_join}\NormalTok{(movie_titles, }\DataTypeTok{by=}\StringTok{"movieId"}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{arrange}\NormalTok{(b_i) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{slice}\NormalTok{(}\DecValTok{1}\OperatorTok{:}\DecValTok{10}\NormalTok{)  }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{pull}\NormalTok{(title)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] "Besotted (2001)"                          
##  [2] "Hi-Line, The (1999)"                      
##  [3] "Accused (Anklaget) (2005)"                
##  [4] "Confessions of a Superhero (2007)"        
##  [5] "War of the Worlds 2: The Next Wave (2008)"
##  [6] "SuperBabies: Baby Geniuses 2 (2004)"      
##  [7] "Disaster Movie (2008)"                    
##  [8] "From Justin to Kelly (2003)"              
##  [9] "Hip Hop Witch, Da (2000)"                 
## [10] "Criminals (1996)"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{train_set }\OperatorTok{%>%}\StringTok{ }\KeywordTok{count}\NormalTok{(movieId) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{left_join}\NormalTok{(movie_avgs, }\DataTypeTok{by=}\StringTok{"movieId"}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{left_join}\NormalTok{(movie_titles, }\DataTypeTok{by=}\StringTok{"movieId"}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{arrange}\NormalTok{(}\KeywordTok{desc}\NormalTok{(b_i)) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{slice}\NormalTok{(}\DecValTok{1}\OperatorTok{:}\DecValTok{10}\NormalTok{) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{pull}\NormalTok{(n)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] 1 1 1 1 1 1 4 2 4 4
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{train_set }\OperatorTok{%>%}\StringTok{ }\KeywordTok{count}\NormalTok{(movieId) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{left_join}\NormalTok{(movie_avgs) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{left_join}\NormalTok{(movie_titles, }\DataTypeTok{by=}\StringTok{"movieId"}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{arrange}\NormalTok{(b_i) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{slice}\NormalTok{(}\DecValTok{1}\OperatorTok{:}\DecValTok{10}\NormalTok{) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{pull}\NormalTok{(n)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1]   1   1   1   1   2  47  30 183  11   1
\end{verbatim}

\hypertarget{lambda---a-tuning-parameter}{%
\subsection{Lambda - a tuning
parameter}\label{lambda---a-tuning-parameter}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{qplot}\NormalTok{(lambdas, rmses)  }
\end{Highlighting}
\end{Shaded}

\includegraphics{MovieLens_RecommendationSystem_files/figure-latex/resplot-1.pdf}
\# Result and Conclusion \#\#\# RMSE improved from initial estimation
from mean

\hypertarget{method-rmse}{%
\subsubsection{\textbar{} Method \textbar{} RMSE
\textbar{}}\label{method-rmse}}

\hypertarget{section}{%
\subsubsection{\textbar------------------------------------\textbar------------\textbar{}}\label{section}}

\hypertarget{average-1.060054}{%
\subsubsection{\textbar{} Average \textbar{} 1.060054
\textbar{}}\label{average-1.060054}}

\hypertarget{movie-effect-0.9421695}{%
\subsubsection{\textbar{} Movie effect \textbar{} 0.9421695
\textbar{}}\label{movie-effect-0.9421695}}

\hypertarget{movie-and-user-effects-0.8646843}{%
\subsubsection{\textbar{} Movie and user effects \textbar{} 0.8646843
\textbar{}}\label{movie-and-user-effects-0.8646843}}

\hypertarget{regularized-movie-and-user-effect-0.8641362}{%
\subsubsection{\textbar{} Regularized movie and user effect \textbar{}
0.8641362
\textbar{}}\label{regularized-movie-and-user-effect-0.8641362}}

\hypertarget{reference}{%
\section{Reference}\label{reference}}

\hypertarget{httpsrafalab.github.iodsbooklarge-datasets.htmlrecommendation-systems}{%
\subsubsection{\texorpdfstring{\url{https://rafalab.github.io/dsbook/large-datasets.html\#recommendation-systems}}{https://rafalab.github.io/dsbook/large-datasets.html\#recommendation-systems}}\label{httpsrafalab.github.iodsbooklarge-datasets.htmlrecommendation-systems}}

\end{document}
